"""Load the synthetic vision dataset produced by the Blender renderer.

The dataset (`Vision/synthetic_data/ground_truth.json`) is generated by
`DigitalTwin/scripts/render_vision_dataset.py`, which must be run inside Blender first
(it can't run in a plain Python environment). Until then these loaders raise a clear
error pointing at that step.
"""

import json
import os

_HERE = os.path.dirname(os.path.abspath(__file__))          # Vision/perception
_REPO = os.path.dirname(os.path.dirname(_HERE))             # repo root

SYNTHETIC_DATA_DIR = os.path.join(_REPO, "Vision", "synthetic_data")
GROUND_TRUTH_JSON = os.path.join(SYNTHETIC_DATA_DIR, "ground_truth.json")


def load_ground_truth(path=GROUND_TRUTH_JSON):
    """Return the parsed ground_truth.json, or raise a clear error if it's missing."""
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"{path} not found. Generate it first by running "
            "DigitalTwin/scripts/render_vision_dataset.py inside Blender "
            "(see that script's docstring)."
        )
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_calibration_points(ground_truth):
    """Return (pixel_points, world_points) from the camera calibration correspondences,
    in matching order — ready to pass to homography.compute_homography."""
    correspondences = ground_truth["camera_calibration"]["correspondences"]
    pixel_points = [c["pixel"] for c in correspondences]
    world_points = [c["world"] for c in correspondences]
    return pixel_points, world_points


def iter_people(ground_truth):
    """Yield (scene, person) for every person across all scenes (single + multi)."""
    for scene in ground_truth["scenes"]:
        for person in scene["people"]:
            yield scene, person
