"""
Guardian AI – RF Propagation Simulator
Phase 2: Digital Twin → RF Simulation

What this does:
- Reads seat_map.json (generated by Blender script)
- Models 4 RF nodes at ceiling corners
- Calculates expected RSSI at every seat using log-distance path loss + wall attenuation
- Adds realistic noise
- Generates synthetic RSSI fingerprint dataset for localization training
- Saves results to rssi_fingerprint.json and rssi_dataset.csv

How to run:
    python rf_propagation_simulator.py

Requirements:
    pip install numpy pandas matplotlib
"""

import json
import math
import random
import csv
import os
import numpy as np

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))            # DigitalTwin/scripts
REPO_ROOT  = os.path.dirname(os.path.dirname(SCRIPT_DIR))          # repo root
SEAT_MAP_PATH     = os.path.join(REPO_ROOT, "Shared", "seat_map.json")
TRAINING_DATA_DIR = os.path.join(REPO_ROOT, "AI", "training_data")           # rssi_fingerprint.json, rssi_dataset.csv
RF_SIM_DIR        = os.path.join(REPO_ROOT, "DigitalTwin", "rf_simulation")  # simulation_report.txt, best_node_placement.json

# RF Node positions (X, Y, Z) in meters — loaded from the node placement optimizer's
# own output so this simulator can't silently drift from the confirmed layout.
_RF_NODE_IDS = [
    "RF_NODE_01_FrontLeft", "RF_NODE_02_FrontRight",
    "RF_NODE_03_BackLeft", "RF_NODE_04_BackRight",
]

def load_rf_nodes(path):
    with open(path, "r") as f:
        best = json.load(f)
    nodes = best["nodes"]
    if len(nodes) != len(_RF_NODE_IDS):
        raise ValueError(f"Expected {len(_RF_NODE_IDS)} RF nodes in {path}, found {len(nodes)}")
    return [{"node_id": node_id, **node} for node_id, node in zip(_RF_NODE_IDS, nodes)]

RF_NODES = load_rf_nodes(os.path.join(RF_SIM_DIR, "best_node_placement.json"))

# Log-distance path loss model parameters for 2.4 GHz indoor
FREQ_GHZ        = 2.437   # BLE advertising channel
TX_POWER_DBM    = 0.0     # Transmitter power (0 dBm typical for BLE beacon)
PATH_LOSS_EXP   = 2.8     # Indoor path loss exponent (2.0-4.0, 2.8 typical)
REF_DISTANCE_M  = 1.0     # Reference distance (1 meter)
NOISE_STD_DB    = 3.0     # Gaussian noise standard deviation (dB)
SAMPLES_PER_SEAT = 100    # How many RSSI samples to generate per seat per node

# Wall attenuation (dB) — between transmitter and receiver
WALL_ATTENUATION_DB = 3.0   # Each wall crossing adds this loss

# Reference path loss at 1 meter for 2.4 GHz
# PL0 = 20 * log10(4 * pi * f / c)
def compute_pl0(freq_ghz):
    freq_hz = freq_ghz * 1e9
    c = 3e8
    pl0 = 20 * math.log10((4 * math.pi * freq_hz) / c)
    return pl0

PL0 = compute_pl0(FREQ_GHZ)  # ~40 dB at 1m for 2.4 GHz

# ─────────────────────────────────────────────
# LOAD SEAT MAP
# ─────────────────────────────────────────────

def load_seat_map(path):
    with open(path, "r") as f:
        data = json.load(f)
    print(f"✅ Loaded seat_map.json — {data['total_seats']} seats")
    return data

# ─────────────────────────────────────────────
# PATH LOSS MODEL
# Log-distance: PL(d) = PL0 + 10 * n * log10(d/d0)
# RSSI = TX_Power - PL(d)
# ─────────────────────────────────────────────

def distance_3d(p1, p2):
    return math.sqrt(
        (p1["x"] - p2["x"])**2 +
        (p1["y"] - p2["y"])**2 +
        (p1["z"] - p2["z"])**2
    )

def estimate_rssi(tx_pos, rx_pos, n_walls=0):
    d = distance_3d(tx_pos, rx_pos)
    if d < 0.1:
        d = 0.1  # avoid log(0)

    # Free space path loss at reference distance
    pl0 = PL0

    # Log-distance path loss
    pl = pl0 + 10 * PATH_LOSS_EXP * math.log10(d / REF_DISTANCE_M)

    # Wall attenuation
    wall_loss = n_walls * WALL_ATTENUATION_DB

    # RSSI (dBm)
    rssi = TX_POWER_DBM - pl - wall_loss

    return rssi

def add_noise(rssi):
    noise = random.gauss(0, NOISE_STD_DB)
    return rssi + noise

# ─────────────────────────────────────────────
# WALL CROSSING ESTIMATOR
# Simple approximation: count walls between tx and rx
# In our hall there are no internal walls, so 0 for most paths
# Benches cause slight obstruction modeled as fractional wall
# ─────────────────────────────────────────────

def estimate_wall_crossings(tx_pos, rx_pos, hall_config):
    """
    Simple wall crossing count.
    No internal walls in this hall.
    Bench rows cause slight obstruction.
    """
    # No internal walls — return 0 base crossings
    # Could be extended to model wall crossings for multi-room scenarios
    return 0

# ─────────────────────────────────────────────
# GENERATE RSSI FINGERPRINT DATASET
# ─────────────────────────────────────────────

def generate_fingerprint_dataset(seat_map_data):
    seats = seat_map_data["seats"]
    hall  = seat_map_data["hall"]

    fingerprint_db  = []   # one entry per seat (mean RSSI vector)
    full_dataset    = []   # one entry per sample (for ML training)

    print(f"\n📡 Simulating RSSI for {len(seats)} seats x {len(RF_NODES)} nodes x {SAMPLES_PER_SEAT} samples...")
    print(f"   Frequency:     {FREQ_GHZ} GHz")
    print(f"   Path loss exp: {PATH_LOSS_EXP}")
    print(f"   Noise std:     {NOISE_STD_DB} dB")
    print(f"   TX power:      {TX_POWER_DBM} dBm\n")

    for seat in seats:
        seat_pos = {"x": seat["x"], "y": seat["y"], "z": seat["z"]}

        # Calculate mean RSSI from each node
        mean_rssi_vector = {}
        std_rssi_vector  = {}

        for node in RF_NODES:
            node_pos = {"x": node["x"], "y": node["y"], "z": node["z"]}
            n_walls  = estimate_wall_crossings(node_pos, seat_pos, hall)

            # True mean RSSI (no noise)
            true_rssi = estimate_rssi(node_pos, seat_pos, n_walls)

            # Generate multiple noisy samples
            samples = [add_noise(true_rssi) for _ in range(SAMPLES_PER_SEAT)]

            mean_rssi = np.mean(samples)
            std_rssi  = np.std(samples)

            mean_rssi_vector[node["node_id"]] = round(mean_rssi, 2)
            std_rssi_vector[node["node_id"]]  = round(std_rssi, 2)

            # Add each sample to full dataset
            for i, sample in enumerate(samples):
                full_dataset.append({
                    "sample_id":   f"{seat['seat_id']}_N{RF_NODES.index(node)+1}_S{i+1:03d}",
                    "seat_id":     seat["seat_id"],
                    "row":         seat["row"],
                    "section":     seat["section"],
                    "seat_number": seat["seat_number"],
                    "true_x":      seat["x"],
                    "true_y":      seat["y"],
                    "true_z":      seat["z"],
                    "node_id":     node["node_id"],
                    "rssi_dbm":    round(sample, 2),
                    "true_rssi":   round(true_rssi, 2),
                    "distance_m":  round(distance_3d(node_pos, seat_pos), 3),
                })

        # Fingerprint entry — mean RSSI vector for this seat
        fingerprint_entry = {
            "seat_id":     seat["seat_id"],
            "row":         seat["row"],
            "section":     seat["section"],
            "seat_number": seat["seat_number"],
            "x":           seat["x"],
            "y":           seat["y"],
            "z":           seat["z"],
            "rssi_node1":  mean_rssi_vector["RF_NODE_01_FrontLeft"],
            "rssi_node2":  mean_rssi_vector["RF_NODE_02_FrontRight"],
            "rssi_node3":  mean_rssi_vector["RF_NODE_03_BackLeft"],
            "rssi_node4":  mean_rssi_vector["RF_NODE_04_BackRight"],
            "std_node1":   std_rssi_vector["RF_NODE_01_FrontLeft"],
            "std_node2":   std_rssi_vector["RF_NODE_02_FrontRight"],
            "std_node3":   std_rssi_vector["RF_NODE_03_BackLeft"],
            "std_node4":   std_rssi_vector["RF_NODE_04_BackRight"],
        }
        fingerprint_db.append(fingerprint_entry)

    print(f"✅ Generated {len(full_dataset)} total samples")
    print(f"✅ Fingerprint DB: {len(fingerprint_db)} seat entries")
    return fingerprint_db, full_dataset

# ─────────────────────────────────────────────
# SAVE OUTPUTS
# ─────────────────────────────────────────────

def save_outputs(fingerprint_db, full_dataset, seat_map_data):
    os.makedirs(TRAINING_DATA_DIR, exist_ok=True)
    os.makedirs(RF_SIM_DIR, exist_ok=True)

    # 1. Fingerprint database JSON
    fingerprint_path = os.path.join(TRAINING_DATA_DIR, "rssi_fingerprint.json")
    output = {
        "project": "Guardian AI",
        "version": "1.0",
        "description": "Synthetic RSSI fingerprint database for localization",
        "frequency_ghz": FREQ_GHZ,
        "path_loss_exponent": PATH_LOSS_EXP,
        "tx_power_dbm": TX_POWER_DBM,
        "noise_std_db": NOISE_STD_DB,
        "samples_per_seat": SAMPLES_PER_SEAT,
        "rf_nodes": RF_NODES,
        "total_seats": len(fingerprint_db),
        "fingerprints": fingerprint_db
    }
    with open(fingerprint_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"✅ rssi_fingerprint.json → {fingerprint_path}")

    # 2. Full dataset CSV (for ML training)
    csv_path = os.path.join(TRAINING_DATA_DIR, "rssi_dataset.csv")
    if full_dataset:
        keys = full_dataset[0].keys()
        with open(csv_path, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=keys)
            writer.writeheader()
            writer.writerows(full_dataset)
    print(f"✅ rssi_dataset.csv    → {csv_path}")

    # 3. Summary report
    report_path = os.path.join(RF_SIM_DIR, "simulation_report.txt")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("Guardian AI – RF Propagation Simulation Report\n")
        f.write("=" * 50 + "\n\n")
        f.write(f"Hall dimensions:     {seat_map_data['hall']['X']}m x {seat_map_data['hall']['Y']}m x {seat_map_data['hall']['Z']}m\n")
        f.write(f"Total seats:         {len(fingerprint_db)}\n")
        f.write(f"RF nodes:            {len(RF_NODES)}\n")
        f.write(f"Frequency:           {FREQ_GHZ} GHz\n")
        f.write(f"Path loss exponent:  {PATH_LOSS_EXP}\n")
        f.write(f"TX power:            {TX_POWER_DBM} dBm\n")
        f.write(f"Noise std dev:       {NOISE_STD_DB} dB\n")
        f.write(f"Samples per seat:    {SAMPLES_PER_SEAT}\n")
        f.write(f"Total samples:       {len(full_dataset)}\n\n")
        f.write("RF Node Positions:\n")
        for node in RF_NODES:
            f.write(f"  {node['node_id']}: ({node['x']}, {node['y']}, {node['z']})\n")
        f.write("\nSample RSSI values (first 5 seats):\n")
        for fp in fingerprint_db[:5]:
            f.write(f"  {fp['seat_id']} → N1:{fp['rssi_node1']} N2:{fp['rssi_node2']} N3:{fp['rssi_node3']} N4:{fp['rssi_node4']} dBm\n")

    print(f"✅ simulation_report.txt → {report_path}")

# ─────────────────────────────────────────────
# PRINT RSSI HEATMAP (text version)
# ─────────────────────────────────────────────

def print_rssi_summary(fingerprint_db):
    print("\n📊 RSSI Summary (mean across all seats per node):")
    for i, node in enumerate(RF_NODES, 1):
        key = f"rssi_node{i}"
        values = [fp[key] for fp in fingerprint_db]
        print(f"  {node['node_id']}:")
        print(f"    Min: {min(values):.1f} dBm  Max: {max(values):.1f} dBm  Mean: {sum(values)/len(values):.1f} dBm")

    print("\n📍 Sample seat RSSI vectors:")
    sample_seats = [fingerprint_db[0], fingerprint_db[49], fingerprint_db[98]]
    for fp in sample_seats:
        print(f"  {fp['seat_id']} (x={fp['x']}, y={fp['y']}):")
        print(f"    N1={fp['rssi_node1']} N2={fp['rssi_node2']} N3={fp['rssi_node3']} N4={fp['rssi_node4']} dBm")

# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────

def main():
    print("\n🚀 Guardian AI RF Propagation Simulator starting...\n")

    random.seed(42)  # fixed seed so reruns are deterministic/diffable

    # Load seat map
    seat_map_data = load_seat_map(SEAT_MAP_PATH)

    # Generate RSSI fingerprint dataset
    fingerprint_db, full_dataset = generate_fingerprint_dataset(seat_map_data)

    # Print summary
    print_rssi_summary(fingerprint_db)

    # Save all outputs
    print(f"\n💾 Saving outputs to {TRAINING_DATA_DIR} and {RF_SIM_DIR}")
    save_outputs(fingerprint_db, full_dataset, seat_map_data)

    print("\n✅ RF Propagation Simulation complete!")
    print(f"\nOutputs saved to: {TRAINING_DATA_DIR} and {RF_SIM_DIR}")
    print("  rssi_fingerprint.json  — fingerprint DB for localization")
    print("  rssi_dataset.csv       — full dataset for ML training")
    print("  simulation_report.txt  — simulation summary")
    print("\nNext step: Person 2 (AI) uses rssi_dataset.csv to train the localization model.")

main()
